server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: FOOD_CATALOGUE_SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/foodCatalougeDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
